version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3400:3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d